# Generated by Django 2.2.3 on 2019-11-19 19:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Documnet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, verbose_name='عنوان')),
                ('doc_file', models.FileField(upload_to='income/static/contracts/Documents', verbose_name='فایل')),
                ('created_date', models.DateField(default='Tue Nov 19 19:22:30 2019', verbose_name='تاریخ ایجاد')),
                ('added_by_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='کاربر ایجاد کننده')),
            ],
        ),
    ]
