# Generated by Django 2.2.3 on 2019-11-19 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('docmanagment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, verbose_name='عنوان')),
            ],
        ),
        migrations.AlterField(
            model_name='documnet',
            name='created_date',
            field=models.DateField(default='Tue Nov 19 19:27:07 2019', verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='documnet',
            name='title',
            field=models.CharField(max_length=60, verbose_name='عنوان سند'),
        ),
        migrations.AddField(
            model_name='documnet',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='docmanagment.Category', verbose_name='عنوان گروه'),
        ),
    ]
