# Generated by Django 2.2.3 on 2019-11-26 03:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('docmanagment', '0002_auto_20191119_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documnet',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2019, 11, 26, 3, 18, 36, 425681, tzinfo=utc), verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='documnet',
            name='doc_file',
            field=models.ImageField(upload_to='photos/', verbose_name='فایل'),
        ),
    ]
