# Generated by Django 2.2.3 on 2019-11-27 05:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('docmanagment', '0004_auto_20191126_0322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documnet',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2019, 11, 27, 5, 44, 35, 632771, tzinfo=utc), verbose_name='تاریخ ایجاد'),
        ),
    ]
