# Generated by Django 2.2.3 on 2019-11-29 06:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('docmanagment', '0013_auto_20191128_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documnet',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2019, 11, 29, 6, 32, 51, 2058, tzinfo=utc), verbose_name='تاریخ ایجاد'),
        ),
    ]
