# Generated by Django 2.2.3 on 2019-11-29 08:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('docmanagment', '0014_auto_20191129_0632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documnet',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2019, 11, 29, 8, 35, 44, 449552, tzinfo=utc), verbose_name='تاریخ ایجاد'),
        ),
    ]
