# Generated by Django 2.2.3 on 2019-11-29 08:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docmanagment', '0023_auto_20191129_0840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documnet',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2019, 11, 29, 8, 40, 51, 322736), verbose_name='تاریخ ایجاد'),
        ),
    ]
