# Generated by Django 2.2.3 on 2019-11-29 09:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docmanagment', '0024_auto_20191129_0840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documnet',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2019, 11, 29, 9, 8, 50, 878440), verbose_name='تاریخ ایجاد'),
        ),
    ]
