# Generated by Django 2.2.3 on 2019-11-29 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docmanagment', '0025_auto_20191129_0908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documnet',
            name='created_date',
            field=models.DateField(verbose_name='تاریخ ایجاد'),
        ),
    ]
