# Generated by Django 2.2.3 on 2019-11-26 03:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='نام بانک')),
                ('branch_name', models.CharField(max_length=50, verbose_name='نام شعبه')),
                ('account_number', models.CharField(max_length=50, verbose_name='شماره حساب')),
                ('shaba_number', models.CharField(max_length=27, verbose_name='شماره شبا')),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='نام شهر')),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان قرارداد')),
                ('number', models.CharField(max_length=50, verbose_name='شماره قرارداد')),
                ('date', models.DateField(verbose_name='تاریخ شروع')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='تاریخ پایان')),
                ('gross_amount', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='مبلغ اولیه قرارداد')),
                ('adjustment_amount', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='مبلغ تعدیل')),
                ('final_amount', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='مبلغ نهایی قرارداد')),
                ('total_payments', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='مجموع مبالغ دریافتی')),
                ('progress', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='درصد پیشرفت')),
                ('scan_file', models.FileField(blank=True, upload_to='income/static/contracts', verbose_name='فایل قرارداد')),
                ('description', models.CharField(blank=True, max_length=100, verbose_name='توضیحات')),
            ],
        ),
        migrations.CreateModel(
            name='Employeer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='نام کارفرما')),
                ('national_code', models.CharField(max_length=11, verbose_name='شناسه ملی')),
                ('economic_id', models.CharField(max_length=11, verbose_name='شماره اقتصادی')),
                ('phone_number', models.CharField(max_length=11, verbose_name='شماره تلفن')),
                ('address', models.TextField(verbose_name='آدرس')),
                ('description', models.CharField(blank=True, max_length=100, null=True, verbose_name='توضیحات')),
                ('city_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='baseinfo.City', verbose_name='شهر')),
            ],
        ),
        migrations.CreateModel(
            name='FinancialYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='سال مالی')),
                ('is_deleted', models.BooleanField()),
                ('description', models.TextField(verbose_name='توضیحات')),
            ],
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='عنوان پرداخت')),
                ('year', models.IntegerField(choices=[(1396, '1396'), (1397, '1397'), (1398, '1398'), (1399, '1399'), (1400, '1400')], verbose_name='سال')),
                ('month', models.IntegerField(choices=[(1, 'فروردین'), (2, 'اردیبشت'), (3, 'خرداد'), (3, 'تیر'), (5, 'مرداد'), (6, 'شهریور'), (7, 'مهر'), (8, 'آبان'), (9, 'آذر'), (10, 'دی'), (11, 'بهمن'), (12, 'اسفند')], verbose_name='ماه')),
                ('day', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12'), (13, '13'), (14, '14'), (15, '15'), (16, '16'), (17, '17'), (18, '18'), (19, '19'), (20, '20'), (21, '21'), (22, '22'), (23, '23'), (24, '24'), (25, '25'), (26, '26'), (27, '27'), (28, '28'), (29, '29'), (30, '30'), (31, '31')], verbose_name='روز')),
                ('doc_number', models.CharField(max_length=30, verbose_name='شماره سند')),
                ('gross_amount', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='مبلغ ناخالص')),
                ('VAT_included', models.BooleanField(choices=[(True, 'مشمول'), (False, 'معاف')], default=True, verbose_name='مالیات بر ارزش افزوده ')),
                ('VAT_amount', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='مبلغ ارزش افزوده')),
                ('tax_included', models.BooleanField(choices=[(True, 'مشمول'), (False, 'معاف')], default=True, verbose_name='وضعیت مالیات تکلیفی')),
                ('tax_amount', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='مبلغ مالیات')),
                ('pay_amount', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='خالص پرداختی')),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('bank', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='baseinfo.Bank', verbose_name='بانک')),
                ('contract', models.ForeignKey(max_length=150, on_delete=django.db.models.deletion.CASCADE, to='baseinfo.Contract', verbose_name='قرارداد')),
                ('employeer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseinfo.Employeer', verbose_name='کارفرما')),
            ],
            options={
                'ordering': ['year', 'month', 'day'],
            },
        ),
        migrations.AddField(
            model_name='contract',
            name='employer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseinfo.Employeer', verbose_name='کارفرما'),
        ),
        migrations.CreateModel(
            name='Buy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_fname', models.CharField(blank=True, max_length=50, verbose_name='نام')),
                ('seller_lname', models.CharField(blank=True, max_length=50, verbose_name='نام خانوادگی')),
                ('seller_company', models.CharField(blank=True, max_length=50, verbose_name='عنوان شرکت')),
                ('economic_id', models.CharField(max_length=11, verbose_name='شماره اقتصادی')),
                ('national_code', models.CharField(max_length=11, verbose_name='شماره/شناسه ملی')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='عنوان خرید')),
                ('year', models.IntegerField(choices=[(1396, '1396'), (1397, '1397'), (1398, '1398'), (1399, '1399'), (1400, '1400')], verbose_name='سال')),
                ('month', models.IntegerField(choices=[(1, 'فروردین'), (2, 'اردیبشت'), (3, 'خرداد'), (3, 'تیر'), (5, 'مرداد'), (6, 'شهریور'), (7, 'مهر'), (8, 'آبان'), (9, 'آذر'), (10, 'دی'), (11, 'بهمن'), (12, 'اسفند')], verbose_name='ماه')),
                ('day', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12'), (13, '13'), (14, '14'), (15, '15'), (16, '16'), (17, '17'), (18, '18'), (19, '19'), (20, '20'), (21, '21'), (22, '22'), (23, '23'), (24, '24'), (25, '25'), (26, '26'), (27, '27'), (28, '28'), (29, '29'), (30, '30'), (31, '31')], verbose_name='روز')),
                ('doc_number', models.CharField(max_length=30, verbose_name='شماره فاکتور')),
                ('gross_amount', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='مبلغ ناخالص')),
                ('VAT_included', models.BooleanField(choices=[(True, 'مشمول'), (False, 'معاف')], default=True, verbose_name='مالیات بر ارزش افزوده ')),
                ('VAT_amount', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='مبلغ ارزش افزوده')),
                ('pay_amount', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='مبلغ پرداختی')),
                ('phone_number', models.CharField(max_length=11, verbose_name='شماره تلفن')),
                ('address', models.TextField(blank=True, verbose_name='آدرس')),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('city_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='baseinfo.City', verbose_name='شهر')),
                ('contract', models.ForeignKey(max_length=150, on_delete=django.db.models.deletion.CASCADE, to='baseinfo.Contract', verbose_name='قرارداد')),
                ('employeer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseinfo.Employeer', verbose_name='کارفرما')),
            ],
            options={
                'ordering': ['year', 'month', 'day'],
            },
        ),
    ]
