# Generated by Django 2.2.3 on 2019-11-27 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseinfo', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Employeer',
            new_name='Employer',
        ),
        migrations.RenameField(
            model_name='buy',
            old_name='employeer',
            new_name='employer',
        ),
        migrations.RenameField(
            model_name='income',
            old_name='employeer',
            new_name='employer',
        ),
    ]
