# Generated by Django 2.2.3 on 2019-11-28 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseinfo', '0003_auto_20191128_0516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='national_code',
            field=models.CharField(max_length=11, null=True, verbose_name='شناسه ملی'),
        ),
    ]
