# Generated by Django 2.2.3 on 2019-11-28 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseinfo', '0004_auto_20191128_0517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='economic_id',
            field=models.CharField(max_length=11, null=True, verbose_name='شماره اقتصادی'),
        ),
        migrations.AlterField(
            model_name='employer',
            name='phone_number',
            field=models.CharField(max_length=11, null=True, verbose_name='شماره تلفن'),
        ),
    ]
