# Generated by Django 2.2.3 on 2019-11-28 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseinfo', '0005_auto_20191128_0755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='economic_id',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='شماره اقتصادی'),
        ),
        migrations.AlterField(
            model_name='employer',
            name='national_code',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='شناسه ملی'),
        ),
    ]
