# Generated by Django 2.2.3 on 2019-11-28 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseinfo', '0006_auto_20191128_1024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buy',
            name='city_name',
        ),
        migrations.RemoveField(
            model_name='buy',
            name='contract',
        ),
        migrations.RemoveField(
            model_name='buy',
            name='employer',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='employer',
        ),
        migrations.RemoveField(
            model_name='employer',
            name='city_name',
        ),
        migrations.DeleteModel(
            name='FinancialYear',
        ),
        migrations.RemoveField(
            model_name='income',
            name='bank',
        ),
        migrations.RemoveField(
            model_name='income',
            name='contract',
        ),
        migrations.RemoveField(
            model_name='income',
            name='employer',
        ),
        migrations.DeleteModel(
            name='Bank',
        ),
        migrations.DeleteModel(
            name='Buy',
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='Contract',
        ),
        migrations.DeleteModel(
            name='Employer',
        ),
        migrations.DeleteModel(
            name='Income',
        ),
    ]
