# Generated by Django 2.2.3 on 2019-11-28 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('baseinfo', '0007_auto_20191128_1033'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='سال مالی')),
                ('is_deleted', models.BooleanField()),
                ('description', models.TextField(verbose_name='توضیحات')),
            ],
        ),
    ]
