# Generated by Django 2.2.3 on 2019-11-28 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baseinfo', '0008_financialyear'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='نام شهر')),
            ],
        ),
        migrations.CreateModel(
            name='Employeer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='نام کارفرما')),
                ('national_code', models.CharField(max_length=11, verbose_name='شناسه ملی')),
                ('economic_id', models.CharField(max_length=11, verbose_name='شماره اقتصادی')),
                ('phone_number', models.CharField(max_length=11, verbose_name='شماره تلفن')),
                ('address', models.TextField(verbose_name='آدرس')),
                ('description', models.CharField(blank=True, max_length=100, null=True, verbose_name='توضیحات')),
                ('city_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='baseinfo.City', verbose_name='شهر')),
            ],
        ),
    ]
