# Generated by Django 2.2.3 on 2019-11-29 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseinfo', '0010_auto_20191129_0632'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='نام بانک')),
                ('branch_name', models.CharField(max_length=50, verbose_name='نام شعبه')),
                ('account_number', models.CharField(max_length=50, verbose_name='شماره حساب')),
                ('shaba_number', models.CharField(max_length=27, verbose_name='شماره شبا')),
            ],
        ),
    ]
