# Generated by Django 2.1.7 on 2019-12-05 20:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('baseinfo', '0011_bank'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guarantee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان ضمانت نامه')),
                ('status', models.IntegerField(verbose_name='وضعیت ضمانت نامه')),
                ('issue_date', models.DateField(verbose_name='تاریخ صدور')),
                ('expire_date', models.DateField(verbose_name='تاریخ انقضاء')),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='ایجاد کننده')),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='baseinfo.Bank', verbose_name='نام بانک')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseinfo.Contract', verbose_name='عنوان قرارداد')),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='baseinfo.Employer', verbose_name='کارفرما')),
                ('parent_guarantee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='baseinfo.Guarantee', verbose_name='ضمانت نامه اصلی')),
            ],
        ),
    ]
