# Generated by Django 2.1.7 on 2019-12-06 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseinfo', '0012_guarantee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guarantee',
            name='title',
        ),
        migrations.AddField(
            model_name='guarantee',
            name='guarantee_type',
            field=models.IntegerField(choices=[(1, ' ضمانت نامه پیش پرداخت'), (2, ' ضمانت نامه حسن انجام کار')], default=1, max_length=100, verbose_name='عنوان ضمانت نامه'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='guarantee',
            name='status',
            field=models.IntegerField(choices=[(1, 'صدور'), (2, 'ابطال شد'), (3, 'تمدید')], verbose_name='وضعیت ضمانت نامه'),
        ),
    ]
