# Generated by Django 2.1.7 on 2019-12-06 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseinfo', '0013_auto_20191206_0758'),
    ]

    operations = [
        migrations.AddField(
            model_name='guarantee',
            name='guarntee_Sepam',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='شماره سپام'),
        ),
        migrations.AddField(
            model_name='guarantee',
            name='guarntee_number',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='شماره ضمانت نامه'),
        ),
        migrations.AlterField(
            model_name='guarantee',
            name='guarantee_type',
            field=models.IntegerField(choices=[(1, ' ضمانت نامه شرکت در مناقصه'), (2, ' ضمانت نامه پیش پرداخت'), (3, ' ضمانت نامه حسن انجام کار')], max_length=100, verbose_name='عنوان ضمانت نامه'),
        ),
    ]
