# Generated by Django 2.1.7 on 2019-12-06 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseinfo', '0014_auto_20191206_0804'),
    ]

    operations = [
        migrations.AddField(
            model_name='guarantee',
            name='guarantee_file',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='فایل ضمانت نامه'),
        ),
    ]
