# Generated by Django 2.1.7 on 2019-12-06 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseinfo', '0015_guarantee_guarantee_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guarantee',
            name='guarantee_type',
            field=models.IntegerField(choices=[(1, ' ضمانت نامه شرکت در مناقصه'), (2, ' ضمانت نامه پیش پرداخت'), (3, ' ضمانت نامه حسن انجام کار')], verbose_name='عنوان ضمانت نامه'),
        ),
    ]
