# Generated by Django 2.1.7 on 2019-12-06 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baseinfo', '0017_guarantee_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='نام شرکت')),
                ('register_number', models.CharField(max_length=20, verbose_name='شماره ثبت')),
                ('register_date', models.DateField(verbose_name='')),
                ('national_code', models.CharField(max_length=11, verbose_name='شناسه ملی')),
                ('economic_id', models.CharField(max_length=11, verbose_name='شماره اقتصادی')),
                ('phone_number', models.CharField(max_length=11, verbose_name='شماره تلفن')),
                ('address', models.TextField(verbose_name='آدرس')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='ایمیل')),
                ('site', models.URLField(blank=True, null=True, verbose_name='آدرس سایت')),
                ('description', models.CharField(blank=True, max_length=100, null=True, verbose_name='توضیحات')),
                ('city_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='baseinfo.City', verbose_name='شهر')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50, verbose_name='نام')),
                ('lname', models.CharField(max_length=50, verbose_name='نام خانوادگی')),
                ('father_name', models.CharField(max_length=50, verbose_name='نام پدر')),
                ('national_code', models.CharField(max_length=10, verbose_name='کد ملی')),
                ('id_number', models.CharField(max_length=10, verbose_name='شماره شناسنامه')),
                ('position', models.IntegerField(choices=[(1, 'مدیرعامل'), (2, 'رییس هییت مدیره'), (3, 'نایب رییس هییت مدیره'), (4, 'عضور')], verbose_name='سمت')),
                ('degree', models.IntegerField(choices=[(1, 'دیپلم'), (2, 'کاردانی'), (3, 'کارشناسی'), (4, 'کارشناسی ارشد')], verbose_name='مدرک تحصیلی')),
                ('work_experience', models.IntegerField(verbose_name='سابقه کار')),
                ('field_of_study', models.IntegerField(choices=[(1, 'عمران'), (2, 'مکانیک'), (3, 'کامپیوتر'), (4, 'برق'), (5, 'معماری')], verbose_name='')),
                ('tel', models.CharField(blank=True, max_length=20, null=True, verbose_name='شماره تلفن')),
                ('address', models.TextField(blank=True, null=True, verbose_name='آدرس')),
                ('is_deleted', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='baseinfo.CompanyInfo', verbose_name='نام شرکت')),
            ],
        ),
    ]
