# Generated by Django 2.1.7 on 2019-12-07 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseinfo', '0018_companyinfo_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='number_of_shares',
            field=models.IntegerField(default=0, verbose_name='تعداد سهم'),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='economic_id',
            field=models.CharField(max_length=12, verbose_name='شماره اقتصادی'),
        ),
    ]
