# Generated by Django 2.2.3 on 2019-07-12 02:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employeer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='نام کارفرما')),
                ('description', models.CharField(blank=True, max_length=100, null=True, verbose_name='توضیحات')),
            ],
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='عنوان قرارداد')),
                ('year', models.IntegerField(verbose_name='سال')),
                ('month', models.IntegerField(verbose_name='ماه')),
                ('gross_amount', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='مبلغ ناخالص')),
                ('VAT_included', models.BooleanField(default=True, verbose_name='مشمول ارزش افزوده میباشد؟')),
                ('VAT_amount', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='مبلغ ارزش افزوده')),
                ('tax_included', models.BooleanField(default=True, verbose_name='مشمول مالیات میباشد؟')),
                ('tax_amount', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='مبلغ ارزش افزوده')),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('employeer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='income.Employeer')),
            ],
        ),
    ]
