# Generated by Django 2.2.3 on 2019-07-12 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='مبلغ مالیات'),
        ),
    ]
