# Generated by Django 2.2.3 on 2019-07-12 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0002_auto_20190712_0508'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeer',
            name='national_code',
            field=models.CharField(default=0, max_length=11, verbose_name='شناسه ملی'),
            preserve_default=False,
        ),
    ]
