# Generated by Django 2.2.3 on 2019-07-15 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0003_employeer_national_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='نام بانک')),
                ('brach_name', models.CharField(max_length=50, verbose_name='نام شعبه')),
                ('accout_number', models.CharField(max_length=50, verbose_name='شماره حساب')),
                ('shaba_number', models.CharField(max_length=27, verbose_name='شماره شبا')),
            ],
        ),
    ]
