# Generated by Django 2.2.3 on 2019-07-15 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0004_bank'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='bank',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='income.Bank'),
        ),
        migrations.AddField(
            model_name='income',
            name='day',
            field=models.IntegerField(default=1, verbose_name='روز'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='income',
            name='doc_number',
            field=models.CharField(default=1, max_length=30, verbose_name='شماره سند'),
            preserve_default=False,
        ),
    ]
