# Generated by Django 2.2.3 on 2019-07-15 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0005_auto_20190715_0920'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bank',
            old_name='accout_number',
            new_name='account_number',
        ),
        migrations.RenameField(
            model_name='bank',
            old_name='brach_name',
            new_name='branch_name',
        ),
    ]
