# Generated by Django 2.2.3 on 2019-07-15 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0006_auto_20190715_0925'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='')),
                ('number', models.CharField(max_length=50, verbose_name='')),
                ('date', models.DateField(verbose_name='')),
                ('description', models.CharField(max_length=100, verbose_name='')),
            ],
        ),
        migrations.AlterModelOptions(
            name='income',
            options={'ordering': ['year', 'month', 'day']},
        ),
    ]
