# Generated by Django 2.2.3 on 2019-07-15 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0008_auto_20190715_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='title',
            field=models.CharField(default='sdfsdf', max_length=50),
            preserve_default=False,
        ),
    ]
