# Generated by Django 2.2.3 on 2019-07-15 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0009_income_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='income',
            name='title',
        ),
    ]
