# Generated by Django 2.2.3 on 2019-07-15 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0010_remove_income_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='gross_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='مبلغ قرارداد'),
        ),
    ]
