# Generated by Django 2.2.3 on 2019-07-15 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0011_contract_gross_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='pay_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name=''),
        ),
    ]
