# Generated by Django 2.2.3 on 2019-07-17 23:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0012_income_pay_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='bank',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='income.Bank', verbose_name='بانک'),
        ),
        migrations.AlterField(
            model_name='income',
            name='employeer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='income.Employeer', verbose_name='کارفرما'),
        ),
        migrations.AlterField(
            model_name='income',
            name='pay_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='خالص پرداختی'),
        ),
    ]
