# Generated by Django 2.1.7 on 2019-10-01 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0013_auto_20190717_2355'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='نام شهر')),
            ],
        ),
        migrations.AddField(
            model_name='employeer',
            name='address',
            field=models.TextField(default='test', verbose_name='آدرس'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employeer',
            name='economic_id',
            field=models.CharField(default=11111111, max_length=11, verbose_name='شماره اقتصادی'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employeer',
            name='phone_number',
            field=models.CharField(default=3333333, max_length=11, verbose_name='شماره تلفن'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employeer',
            name='city_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='income.City', verbose_name='شهر'),
        ),
    ]
