# Generated by Django 2.1.7 on 2019-10-10 03:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0014_auto_20191001_1524'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='سال مالی')),
                ('is_deleted', models.BooleanField()),
                ('description', models.TextField(verbose_name='توضیحات')),
            ],
        ),
        migrations.AddField(
            model_name='contract',
            name='employer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='income.Employeer', verbose_name='کارفرما'),
            preserve_default=False,
        ),
    ]
