# Generated by Django 2.1.7 on 2019-10-10 04:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0015_auto_20191010_0337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='employer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='income.Employeer', verbose_name='کارفرما'),
        ),
    ]
