# Generated by Django 2.1.7 on 2019-10-10 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0016_auto_20191010_0403'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='progress',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='درصد پیشرفت'),
        ),
    ]
