# Generated by Django 2.1.7 on 2019-10-10 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0018_income_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='final_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='مبلغ نهایی قرارداد'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='gross_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='مبلغ اولیه قرارداد'),
        ),
    ]
