# Generated by Django 2.1.7 on 2019-10-10 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0019_auto_20191010_0638'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='scan_file',
            field=models.FileField(blank=True, upload_to='', verbose_name='فایل قرارداد'),
        ),
    ]
