# Generated by Django 2.2.3 on 2019-11-15 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0023_auto_20191115_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buy',
            name='address',
            field=models.TextField(blank=True, verbose_name='آدرس'),
        ),
    ]
