# Generated by Django 2.2.3 on 2019-11-19 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0024_auto_20191115_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='buy',
            name='seller_company',
            field=models.CharField(blank=True, max_length=50, verbose_name='عنوان شرکت'),
        ),
        migrations.AddField(
            model_name='buy',
            name='seller_fname',
            field=models.CharField(blank=True, max_length=50, verbose_name='نام'),
        ),
        migrations.AddField(
            model_name='buy',
            name='seller_lname',
            field=models.CharField(blank=True, max_length=50, verbose_name='نام خانوادگی'),
        ),
    ]
