# Generated by Django 2.2.3 on 2019-11-19 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0025_auto_20191119_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ پایان'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='date',
            field=models.DateField(verbose_name='تاریخ شروع'),
        ),
    ]
