# Generated by Django 2.2.3 on 2019-11-29 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baseinfo', '0010_auto_20191129_0632'),
        ('income', '0026_auto_20191119_1826'),
    ]

    operations = [
    #     migrations.RemoveField(
    #         model_name='contract',
    #         name='employer',
    #     ),
    #     migrations.RemoveField(
    #         model_name='employeer',
    #         name='city_name',
    #     ),
    #     migrations.DeleteModel(
    #         name='FinancialYear',
    #     ),
    #     migrations.RemoveField(
    #         model_name='income',
    #         name='employeer',
    #     ),
    #     migrations.AddField(
    #         model_name='income',
    #         name='employer',
    #         field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='baseinfo.Employer', verbose_name='کارفرما'),
    #         preserve_default=False,
    #     ),
    #     migrations.AlterField(
    #         model_name='buy',
    #         name='city_name',
    #         field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='baseinfo.City', verbose_name='شهر'),
    #     ),
    #     migrations.AlterField(
    #         model_name='buy',
    #         name='contract',
    #         field=models.ForeignKey(max_length=150, on_delete=django.db.models.deletion.CASCADE, to='baseinfo.Contract', verbose_name='قرارداد'),
    #     ),
    #     migrations.AlterField(
    #         model_name='income',
    #         name='bank',
    #         field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='baseinfo.Bank', verbose_name='بانک'),
    #     ),
    #     migrations.AlterField(
    #         model_name='income',
    #         name='contract',
    #         field=models.ForeignKey(max_length=150, on_delete=django.db.models.deletion.CASCADE, to='baseinfo.Contract', verbose_name='قرارداد'),
    #     ),
    #     migrations.DeleteModel(
    #         name='Bank',
    #     ),
    #     migrations.DeleteModel(
    #         name='City',
    #     ),
    #     migrations.DeleteModel(
    #         name='Contract',
    #     ),
    #     migrations.DeleteModel(
    #         name='Employeer',
    #     ),
    ]
