# Generated by Django 2.1.7 on 2019-12-06 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0029_auto_20191130_0416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buy',
            name='economic_id',
            field=models.CharField(max_length=12, verbose_name='شماره اقتصادی'),
        ),
    ]
