# Generated by Django 2.2.3 on 2019-07-18 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hesab', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sanad',
            name='bedehkar',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='sanad',
            name='bestankar',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
